### ISSUE TITLE
Coding and Document standard

### ISSUE THREAD

**Issue by blahlicus** [SEGPTeam/EasySerializableConverter#6]
Groupmates, please make sure to follow the MSDN code standard as per this [link](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions).

**Comment by edwardyhsan** [comment]
We also need a document standard. Why don't we use GNU Documentation Standard as per this [link](http://www.gnu.org/prep/standards/standards.html#Documentation).

**Comment by blahlicus** [comment]
OK I agree!
